[package]
name = "pur"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonschema = "0.37.4"
serde = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
tower-lsp = "0.20.0"
tracing = "0.1.44"
